version: '2'

services:
  recommendations-db:
    image: postgres
  recommendations-ms:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - recommendations-db
